<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Admin\Bfs.Core\Bfs.Core.csproj" />
    <ProjectReference Include="..\Bfs.Auth.Contracts\Bfs.Auth.Contracts.csproj" />
  </ItemGroup>

</Project>
