<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Admin\Bfs.Core\Bfs.Core.csproj" />
        <ProjectReference Include="..\Bfs.Stores.Contracts\Bfs.Stores.Contracts.csproj" />
        <ProjectReference Include="..\Bfs.Stores.Data\Bfs.Stores.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\" />
      <Folder Include="Mapper\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>