namespace Admin.App.Constants;

//How to match generated content with a placeHolder in the destination file.
public enum PlaceHolderType
{
    None = 1,
    StartEnd = 2,    //SubstituteStartEndMatchThenReplace,indirect mapping, appears multiple times in the template file
    PlaceHolder = 3, //SubstituteLineMatchThenReplace, indirect mapping, links a template to a certain "Category" appears once in the template file, it has a specific value.
    Marker = 4,      //FindLineAndReplace, direct mappig. links a template to certain property. if the model has same property, it would replace a new line before the PlaceHolder.
    // in general: if TemplateContentType = Embedded => StartEnd, if TemplateContentType = ExternalFile => PlaceHolder
}

// Info about the code snippet that being processed
public enum WriterType
{
    None = 0,
    System = 1,          // Generate and modify files to set up a new system like Stores, StoreExchange
    Component = 2,       // Generate and modify files to set up a new component like Entity CRUD or Report
    Field = 3,           // single field of a component, that uses a function to generate code snippet for the field. like form html input, or DB column.
    FieldSet = 4,        // subset of component fields, that uses a function to generate code snippet for the whole fieldset. like form html fieldset, or DB config.
    Action = 5,          // an entity that represent a function or link in frontend, that uses a function to generate code snippet for the action. like form button, or list action link.
    AngularFramework = 6,  // copy all Angular framework files
}

public enum SaveGeneratedCode //special setting for Sql Having clause
{
    None = 1,
    PerAllWriters = 2,       // Total code generated by all writers is saved in separate file.
    PerWriter = 3,           // each piece of code generated by one writer is saved in separate file. as in the case of frontend matrix fields.
}

//Where to find content of a template. the source of the template content.
public enum TemplateContentType
{
    Embedded = 1,        //Template Content Between Template_Start & Template_End. suits new generated files.
    ExternalFile = 2,    //Template Content found in external file
    WriterProperty = 3,   //MatchingProperty, Template Content is compouted in the writer model. and stored in a model property. with name matches the inLine Marker.  
}

public enum ReportDefinition
{
    None = 1,
    Join = 2,
    QueryColumn = 3,          // computed by reports
    Aggregate = 4,            // computed by reports
}

public enum FilterDefinition
{
    None = 1,
    ValueString = 2,        // filter by like %string%
    ValueNumber = 3,        // filter by number = value
    Lookup = 4,             // filter by ForignKeyId = value
    Range = 5,              // filter by value between min and max
    AggregateRange = 6,     // filter by aggregate value between min and max, // special setting for Sql Having clause
}

public enum ChartDefinition
{
    None = 1,
    Vertical = 2,    
    Horizontal = 3, 
}

public enum CodeType
{
    None = 1,
    Backend = 3,                // Backend C# Code
    Frontend = 4                // Ftonrtend TypeScript & Angular Code
}

public enum DataType
{
    None = 1,               // Default type
    Tables = 2,             // Data tables that stores business data
    Seed = 3,               // Seed tables that stores system data
    Reports = 4             // Reports that read data from DB
}

//internal use only, the logical type of a component that the user chooses when generating code.
public enum ComponentType
{
    None = 1,               // Default type
    Table = 2,              // Data or Seed table    
    Report = 3              // Report component with or without chart
}

public enum ReportType
{
    None = 1,             // Default type
    List = 2,             // Data tables that stores business data
    Compare = 3,          // Seed tables that stores system data
    Trend = 4           // Reports that read data from DB
}

//Used in Definig a system.
public enum SystemTemplateType
{
    None = 0,
    Identity = 1,
    Api = 2,
}

public enum TemplateType
{
    None = 0,
    Generator = 1,
    Modifier = 2,
}

public enum TemplateElementType
{
    None = 0,                   // Default type
    All = 1,                    // Default type
    System = 2,                 // frontend files needed to implement a system
    Api_Project = 3,            // backend files needed to implement a system
    Contracts_Project = 4,      // backend files needed to implement a system
    Data_Project = 5,           // backend files needed to implement a system
    Domain_Project = 6,         // backend files needed to implement a system
    Client_Project = 7,         // backend files needed to implement a system

    Table = 8,                  // All backend & frontend files needed to work with a table
    Report = 9,                 // All backend & frontend files needed to work with a report
    Validator = 10,             // backend files needed to implement validation logic
    List = 11,                  // backend files needed to implement a query for list table, frontend is a list table    
    Matrix = 12,                // backend files needed to implement a query for list table, frontend is a matrix    
    Chart = 13,                 // frontend files needed to implement a chart
    AngularFramework = 14,     // frontend files needed to implement Angular framework
}

public enum FilterType
{
    None = 1,
    Default = 2,
    LookupFilter = 3,           // Filter by Ids of related records => Table.LookupId  = Lookup.Id
    ValueStringFilter = 4,      // Filter by string value           => field like %input%
    ValueNumberFilter = 5,      // Filter by number value           => field = input
}

public enum ActionType
{
    None = 1,
    FrontendLink = 2,
    FrontendFunction = 3,
}

public enum ActionSource
{
    None = 1,
    System = 2,
    Business = 3,
}

public enum ActionLocation
{
    ListHeader = 1,
    ListRow = 2,
    FormHeader = 3,
    FormField = 4,
    ReportHeader = 5,
    ReportRow = 6,
    MatrixHeader = 7,
    MatrixCell = 8,
}

public enum AggregateType
{
    None = 1,
    Sum = 2,
    Average = 3,
    Count = 4
}

public enum ChartElement
{
    None = 1,
    VerticalField = 2,
    HorizontalField = 3
}

public enum FormControlType
{
    None = 1,
    Default = 2,  // Let the System Decide
    Text = 3,
    FormTab = 4,
    Select = 5,
    CheckBox = 6,
    Date = 7,
    TextNumber = 8,
}

// Field in regard to Database storage. field either saved in table or a children tables as forign key
public enum FieldDefinition
{
    Primitive = 1,      // saved in record as: string, number, boolean, date
    Lookup = 2,         // int or long id of a forign key, saved in record as: ClientId, CountryId
    Object = 3,         // saved in record as: json field: Address, FieldValidation
    CustomFieldList = 4,     // saved in record as: json field: CustomFieldList
    ChildrenList = 5,        // saved in different table: 1 to many TabList, TabMatrix
    ChildrenMatrix = 6,      // saved in different table: 1 to many, Holds Matrix Info, TabMatrix
    ComputedField=7,           
}

// Field in regard to code handling and display
public enum BackendDataType
{
    //Primitive Data Types
    DT_Default = 1,                     // Let system decide
    DT_string = 2,                      // string
    DT_bool = 3,                        // boolean
    DT_long = 4,                        // string
    DT_int = 5,                         // number
    DT_decimal = 6,                     // number
    DT_DateTime = 7,                    // date

    // Lookup- Forignkey
    DT_Lookup = 8,                      // lookup field like clientId
    DT_SeedLookup = 9,                  // lookup field like clientId

    // one-to-many Data Types (Forign Key)
    DT_TabList = 10,                    // Formcontrol = TabList
    DT_TabMatrix = 11,                  // Formcontrol = TabMatrix

    // Complex Data Types (saved as Json)
    DT_CustomFieldList = 12,            // An object that is saved in the database as JSON string
    DT_FieldValidation = 13,            // An object that is saved in the database as JSON string

    DT_ToolTipInfo = 14,                // An object that is saved in the database as JSON string
    DT_FormInfo = 15,                   // An object that is saved in the database as JSON string
    DT_ReportInfo = 16,                 // An object that is saved in the database as JSON string
    DT_MatrixInfo = 17,                 // An object that is saved in the database as JSON string

    DT_Computed = 18,                  // Computed field that is saved in the database but not edited by the user.
}

