<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e123ce36-1f4f-4dcd-a99c-c3d54e70f2af</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\V1\Backend\Bfs.Master\Bfs.Master.Api\Bfs.Master.Api.csproj" />
	  <ProjectReference Include="..\..\V1\Frontend\Auth\Bfs.Identity.Web\Bfs.Identity.Web\Bfs.Identity.Web.csproj" />
	  <ProjectReference Include="..\..\V1\Backend\Bfs.Auth\Bfs.Auth.Api\Bfs.Auth.Api.csproj" />
	  <ProjectReference Include="..\..\V1\Backend\Bfs.Stores\Bfs.Stores.Api\Bfs.Stores.Api.csproj" />
  </ItemGroup>

</Project>
