// <auto-generated />
using Bfs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bfs.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InfrastructureDbContext))]
    [Migration("20260223105422_deployments")]
    partial class deployments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.ActionLocationEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ActionLocation", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.ActionTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ActionType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.AggregateTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AggregateType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BackendDataTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BackendDataType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("DbConnection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsClient", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsComponentBusinessActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionLocationId")
                        .HasColumnType("int");

                    b.Property<long>("BfsComponentId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessActionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsComponentBusinessAction", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsComponentEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BfsSystemId")
                        .HasColumnType("bigint");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuPlaceHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryBaseTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsComponent", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsComponentSystemActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionLocationId")
                        .HasColumnType("int");

                    b.Property<long>("BfsComponentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SystemActionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsComponentSystemAction", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsFieldEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BackendDataTypeId")
                        .HasColumnType("int");

                    b.Property<long>("BfsComponentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilterTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsField", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsSystemEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BasePortNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BfsClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("DbPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemTemplateId")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BfsSystem", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BusinessActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BusinessAction", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.ChartElementEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ChartElement", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.CustomFieldDefinitionEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BfsComponentId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldDefinition", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.CustomReportsEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomReports", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.DataTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DataType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.DeploymentAzureEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AppService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BfsSystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishProfilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetVirtualDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DeploymentAzure", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.DeploymentLocalEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AppPoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BfsSystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHttpsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScriptFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetVirtualDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeploymentLocal", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.FilterTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FilterType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.FormControlTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FormControlType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.SystemActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActionTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MatchProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("WriterTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemAction", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.SystemTemplateEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("SystemTemplate", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.WriterTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WriterType", (string)null);
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsClientEntity", b =>
                {
                    b.OwnsMany("Bfs.Core.ObjectFields.CustomField", "CustomFields", b1 =>
                        {
                            b1.Property<long>("BfsClientEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<long?>("CustomFieldDefinitionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BfsClientEntityId", "__synthesizedOrdinal");

                            b1.ToTable("BfsClient");

                            b1.ToJson("CustomFields");

                            b1.WithOwner()
                                .HasForeignKey("BfsClientEntityId");
                        });

                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.BfsFieldEntity", b =>
                {
                    b.OwnsOne("Bfs.Core.ObjectFields.FormInfo", "FormInfo", b1 =>
                        {
                            b1.Property<long>("BfsFieldEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Column")
                                .HasColumnType("int");

                            b1.Property<int?>("FormControlTypeId")
                                .HasColumnType("int");

                            b1.Property<int?>("Row")
                                .HasColumnType("int");

                            b1.HasKey("BfsFieldEntityId");

                            b1.ToTable("BfsField");

                            b1.ToJson("FormInfo");

                            b1.WithOwner()
                                .HasForeignKey("BfsFieldEntityId");
                        });

                    b.OwnsOne("Bfs.Core.ObjectFields.MatrixInfo", "MatrixInfo", b1 =>
                        {
                            b1.Property<long>("BfsFieldEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("HorizontalApi")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ParentApi")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("VerticalApi")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BfsFieldEntityId");

                            b1.ToTable("BfsField");

                            b1.ToJson("MatrixInfo");

                            b1.WithOwner()
                                .HasForeignKey("BfsFieldEntityId");
                        });

                    b.OwnsOne("Bfs.Core.ObjectFields.ReportInfo", "ReportInfo", b1 =>
                        {
                            b1.Property<long>("BfsFieldEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("AggregateTypeId")
                                .HasColumnType("int");

                            b1.Property<int?>("ChartElementId")
                                .HasColumnType("int");

                            b1.Property<bool?>("IsColumnVisible")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsJoinField")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsQueryColumn")
                                .HasColumnType("bit");

                            b1.Property<string>("ParentTable")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BfsFieldEntityId");

                            b1.ToTable("BfsField");

                            b1.ToJson("ReportInfo");

                            b1.WithOwner()
                                .HasForeignKey("BfsFieldEntityId");
                        });

                    b.OwnsOne("Bfs.Core.ObjectFields.ToolTipInfo", "ToolTipInfo", b1 =>
                        {
                            b1.Property<long>("BfsFieldEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("ActionLocationId")
                                .HasColumnType("int");

                            b1.Property<string>("Icon")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Note")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BfsFieldEntityId");

                            b1.ToTable("BfsField");

                            b1.ToJson("ToolTipInfo");

                            b1.WithOwner()
                                .HasForeignKey("BfsFieldEntityId");
                        });

                    b.OwnsOne("Bfs.Core.ObjectFields.FieldValidation", "FieldValidation", b1 =>
                        {
                            b1.Property<long>("BfsFieldEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AllowedValues")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("MaxLength")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MaxValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MinLength")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MinValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RegexPattern")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BfsFieldEntityId");

                            b1.ToTable("BfsField");

                            b1.ToJson("FieldValidation");

                            b1.WithOwner()
                                .HasForeignKey("BfsFieldEntityId");
                        });

                    b.Navigation("FieldValidation")
                        .IsRequired();

                    b.Navigation("FormInfo")
                        .IsRequired();

                    b.Navigation("MatrixInfo")
                        .IsRequired();

                    b.Navigation("ReportInfo")
                        .IsRequired();

                    b.Navigation("ToolTipInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Bfs.Infrastructure.Data.Models.CustomFieldDefinitionEntity", b =>
                {
                    b.OwnsOne("Bfs.Core.ObjectFields.FieldValidation", "FieldValidation", b1 =>
                        {
                            b1.Property<long>("CustomFieldDefinitionEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AllowedValues")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("MaxLength")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MaxValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MinLength")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MinValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RegexPattern")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomFieldDefinitionEntityId");

                            b1.ToTable("CustomFieldDefinition");

                            b1.ToJson("FieldValidation");

                            b1.WithOwner()
                                .HasForeignKey("CustomFieldDefinitionEntityId");
                        });

                    b.Navigation("FieldValidation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
